"""Generate an Allegro 24.1 SKILL bundle for conservative native plane updates."""
from __future__ import annotations

import json
import math
import sqlite3
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from shapely import prepare
from shapely.geometry import Point, Polygon
from shapely.strtree import STRtree

from .spd import parse_spd


class _Report:
    def __init__(self):
        self.counts = Counter()
        self.warnings: dict[str, dict] = {}

    def warn(self, code, message, line=None):
        item = self.warnings.setdefault(code, {"count": 0, "samples": []})
        item["count"] += 1
        if len(item["samples"]) < 5:
            item["samples"].append({"line": line, "message": str(message)})


def _skill_string(value: str) -> str:
    """JSON string quoting is compatible with SKILL for these UTF-8 strings."""
    text = str(value)
    for character in text:
        # SKILL does not understand the \uXXXX escapes json would emit here.
        if ord(character) < 0x20 or ord(character) == 0x7F:
            raise ValueError(
                f"Control character U+{ord(character):04X} cannot be written to SKILL: {text!r}"
            )
    return json.dumps(text, ensure_ascii=False)


def _num(value: float) -> str:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError("Non-finite native geometry")
    return format(value, ".12g")


def _native_layer(name: str) -> str:
    for prefix in ("Signal$", "Plane$"):
        if name.startswith(prefix):
            return name[len(prefix) :]
    return name


_QUAD_SEGS = 32
_TOLERANCE = 1e-9


def _shape(encoded: str, kind: str):
    """Return the lookup geometry and the exact source coordinates.

    A circle is approximated by a *circumscribed* polygon so that the bounding
    box used for lookup never falls inside the true disk.  Containment itself is
    decided analytically by :func:`_contains`; emission stays an exact circle.
    """
    data = json.loads(encoded)
    if kind == "Circle":
        radius = data[2] / math.cos(math.pi / (4 * _QUAD_SEGS))
        return Point(data[:2]).buffer(radius, quad_segs=_QUAD_SEGS), data
    return Polygon(list(zip(data[::2], data[1::2]))), data


def _contains(geometry, circle, hole, hole_circle, hole_data) -> bool:
    """Exact ``parent covers void`` test; circles are handled analytically."""
    if circle is not None:
        x, y, radius = circle
        if hole_circle is not None:
            return math.hypot(hole_circle[0] - x, hole_circle[1] - y) + hole_circle[2] <= radius + _TOLERANCE
        # A disk is convex: it covers a polygon exactly when it covers every vertex.
        return all(
            math.hypot(px - x, py - y) <= radius + _TOLERANCE
            for px, py in zip(hole_data[::2], hole_data[1::2])
        )
    if hole_circle is not None:
        center = Point(hole_circle[:2])
        return geometry.covers(center) and (
            geometry.boundary.distance(center) + _TOLERANCE >= hole_circle[2]
        )
    # Unit conversion leaves coordinates a fraction of a nanometre apart, so the
    # polygon test gets the same tolerance the circle tests use.
    return geometry.covers(hole) or geometry.buffer(_TOLERANCE, quad_segs=1).covers(hole)


def _overlaps(geometry, circle, hole, hole_circle) -> bool:
    """True when parent and void share area rather than only a boundary."""
    if circle is not None:
        x, y, radius = circle
        if hole_circle is not None:
            return math.hypot(hole_circle[0] - x, hole_circle[1] - y) < radius + hole_circle[2] - _TOLERANCE
        return Point(x, y).distance(hole) < radius - _TOLERANCE
    if hole_circle is not None:
        return geometry.distance(Point(hole_circle[:2])) < hole_circle[2] - _TOLERANCE
    return (
        geometry.intersects(hole)
        and not geometry.touches(hole)
        and geometry.buffer(-_TOLERANCE, quad_segs=1).intersects(hole)
    )


def _point_list(data: list[float]) -> str:
    points = list(zip(data[::2], data[1::2]))
    if points[-1] != points[0]:
        points.append(points[0])
    return "list(" + " ".join(f"bsP({_num(x)} {_num(y)})" for x, y in points) + ")"


_SKILL_HEADER = r'''; Generated by BRD-SPD-IPC2581. Requires Allegro X PCB Editor 24.1.
; base.brd must be supplied in this directory by the caller.
bsTxn = nil
bsMM = nil
bsShape = nil
bsPlanes = 0
bsComponents = 0
bsMissingComponents = 0
bsLogPath = "execution.log"
bsResultJsonPath = "result.json"
bsResultBrdPath = "result.brd"

procedure(bsLog(msg)
  let((port)
    port = outfile(bsLogPath "a")
    when(port
      fprintf(port "%s\n" msg)
      close(port)
    )
  )
)

procedure(bsError(message)
  bsLog(strcat("ERROR " message))
  error(message)
)

procedure(bsResult(status errorText)
  let((port)
    port = outfile(bsResultJsonPath "w")
    unless(port bsError("Cannot write result.json"))
    if(equal(status "success") then
      fprintf(port "{\"status\":\"success\",\"result_brd\":\"%s\",\"execution_log\":\"%s\",\"planes_replaced\":%d,\"components_updated\":%d,\"components_missing\":%d}\n"
        bsResultBrdPath bsLogPath bsPlanes bsComponents bsMissingComponents)
    else
      fprintf(port "{\"status\":\"%s\",\"error\":\"%s\",\"execution_log\":\"%s\"}\n"
        status errorText bsLogPath)
    )
    close(port)
  )
)

procedure(bsP(x y) list(x * bsMM y * bsMM))
procedure(bsL(value) value * bsMM)

; axlSelectByName populates the current selection set and obeys the user's Find
; Filter, so it can clobber an interactive selection and miss existing objects.
; Look objects up directly first and only fall back to a filtered selection.
procedure(bsFindNet(netName)
  let((found)
    found = axlDBFindByName('net netName)
    if(found then
      bsLog(sprintf(nil "Resolved net %s with axlDBFindByName" netName))
    else
      axlClearSelSet()
      axlSetFindFilter(?enabled '(noall nets) ?onButtons '(nets))
      axlSelectByName("NET" netName)
      found = car(axlGetSelSet())
      axlClearSelSet()
      when(found
        bsLog(sprintf(nil "Resolved net %s with the Find Filter selection fallback" netName))
      )
    )
    found
  )
)

procedure(bsFindComponent(refdes)
  let((found)
    found = axlDBFindByName('refdes refdes)
    when(found && null(found->symbol)
      ; A hit without a placed symbol must not suppress the fallback lookup.
      bsLog(sprintf(nil "axlDBFindByName returned an unplaced %s; trying the Find Filter" refdes))
      found = nil
    )
    if(found then
      bsLog(sprintf(nil "Resolved component %s with axlDBFindByName" refdes))
    else
      axlClearSelSet()
      axlSetFindFilter(?enabled '(noall comps) ?onButtons '(comps))
      axlSelectByName("COMPREFDES" refdes)
      found = car(axlGetSelSet())
      axlClearSelSet()
      when(found
        bsLog(sprintf(nil "Resolved component %s with the Find Filter selection fallback" refdes))
      )
    )
    found
  )
)

procedure(bsValidate(layerName netName)
  unless(axlGetParam(strcat("paramLayerGroup:ETCH/paramLayer:" layerName))
    bsError(sprintf(nil "Missing ETCH layer: %s" layerName))
  )
  unless(bsFindNet(netName)
    bsError(sprintf(nil "Missing net: %s" netName))
  )
)

procedure(bsDeletePlane(layerName netName)
  let((shape skipped)
    skipped = 0
    foreach(shape copy(axlDBGetShapes(strcat("BOUNDARY/" layerName)))
      when(shape->net && equal(shape->net->name netName)
        unless(axlDeleteObject(shape)
          bsError(sprintf(nil "Could not delete dynamic plane %s/%s" layerName netName))
        )
      )
    )
    foreach(shape copy(axlDBGetShapes(strcat("ETCH/" layerName)))
      when(shape->net && equal(shape->net->name netName)
        ; Only independent static copper is replaced; auto-generated fill and
        ; dynamic boundaries stay with the shape that owns them.
        if(!shape->shapeBoundary && !shape->shapeIsBoundary && !shape->shapeAuto then
          unless(axlDeleteObject(shape)
            bsError(sprintf(nil "Could not delete static plane %s/%s" layerName netName))
          )
        else
          skipped = skipped + 1
        )
      )
    )
    when(skipped > 0
      bsLog(sprintf(nil "Skipped %d dynamic/auto-generated ETCH shapes on %s/%s" skipped layerName netName))
    )
  )
)

procedure(bsBeginPolygon(layerName netName points)
  let((path)
    path = axlPathStart(points)
    unless(path bsError("Could not construct polygon path"))
    bsShape = axlDBCreateOpenShape(path t strcat("ETCH/" layerName) netName)
    unless(bsShape bsError(sprintf(nil "Could not create plane %s/%s" layerName netName)))
  )
)

procedure(bsBeginCircle(layerName netName x y radius)
  let((path)
    path = axlPathStartCircle(list(bsP(x y) bsL(radius)) 0.0)
    unless(path bsError("Could not construct circular plane path"))
    bsShape = axlDBCreateOpenShape(path t strcat("ETCH/" layerName) netName)
    unless(bsShape bsError(sprintf(nil "Could not create circular plane %s/%s" layerName netName)))
  )
)

procedure(bsPolygonVoid(points)
  let((path)
    path = axlPathStart(points)
    unless(path && axlDBCreateVoid(bsShape path)
      bsError("Could not create polygon plane void")
    )
  )
)

procedure(bsCircleVoid(x y radius)
  unless(axlDBCreateVoidCircle(bsShape list(bsP(x y) bsL(radius)) 0.0)
    bsError("Could not create circular plane void")
  )
)

procedure(bsEndPlane()
  unless(axlDBCreateCloseShape(bsShape)
    bsError("Could not close/fill plane shape")
  )
  bsShape = nil
  bsPlanes = bsPlanes + 1
  when(mod(bsPlanes 100) == 0
    bsLog(sprintf(nil "Created %d plane shapes" bsPlanes))
  )
)

procedure(bsUpdateComponent(refdes x y rotation expectedMirrored)
  let((component symbol actualMirrored dx dy da moved)
    component = bsFindComponent(refdes)
    if(null(component) || null(component->symbol) then
      bsMissingComponents = bsMissingComponents + 1
      bsLog(sprintf(nil "UNSUPPORTED missing/unplaced component: %s" refdes))
      bsError(sprintf(nil "Cannot update missing/unplaced component: %s" refdes))
    else
      symbol = component->symbol
      actualMirrored = symbol->mirrorType && !equal(symbol->mirrorType "NO")
      unless(equal(actualMirrored expectedMirrored)
        bsError(sprintf(nil "Component side differs from SPD: %s" refdes))
      )
      da = rotation - symbol->rotation
      ; Whether Allegro applies ?move before ?angle is unverified, so rotate
      ; about the symbol's current origin first (which does not move it), then
      ; move it from wherever it now is to the target location.
      unless(da == 0.0
        moved = axlTransformObject(symbol ?angle da ?origin list(xCoord(symbol->xy) yCoord(symbol->xy)) ?allOrNone t)
        unless(moved bsError(sprintf(nil "Could not rotate component: %s" refdes)))
      )
      dx = bsL(x) - xCoord(symbol->xy)
      dy = bsL(y) - yCoord(symbol->xy)
      unless(dx == 0.0 && dy == 0.0
        moved = axlTransformObject(symbol ?move list(dx dy) ?allOrNone t)
        unless(moved bsError(sprintf(nil "Could not move component: %s" refdes)))
      )
      bsComponents = bsComponents + 1
    )
  )
)
'''


_SKILL_FOOTER = r'''procedure(bsIsBaseDesign(name)
  let((base)
    base = lowerCase(name)
    when(rindex(base "/") base = substring(rindex(base "/") 2))
    when(rindex(base "\\") base = substring(rindex(base "\\") 2))
    equal(base "base.brd") || equal(base "base")
  )
)

procedure(bsMain()
  unless(isFile("base.brd") bsError("base.brd is missing"))
  ; allegro -s run.scr base.brd may already have base.brd open; opening it a
  ; second time can prompt, which would hang under -nograph.
  if(axlCurrentDesign() then
    if(bsIsBaseDesign(axlCurrentDesign()) then
      bsLog("base.brd already open; skipping axlOpenDesignForBatch")
    else
      bsError(sprintf(nil "Another design is already open: %s" axlCurrentDesign()))
    )
  else
    unless(axlOpenDesignForBatch("base.brd" "wf") bsError("Could not open base.brd"))
  )
  bsMM = axlMKSConvert(1.0 "mm" car(axlDBGetDesignUnits()))
  unless(bsMM bsError("Could not convert millimeters to active BRD units"))
  bsLog("Opened base.brd; validating requested layers and nets")
  bsValidateAll()
  bsTxn = axlDBTransactionStart()
  unless(bsTxn bsError("Could not start Allegro database transaction"))
  bsApply()
  when(bsMissingComponents > 0
    bsError(sprintf(nil "%d component(s) could not be updated" bsMissingComponents))
  )
  unless(axlDBTransactionCommit(bsTxn)
    bsError("Could not commit database transaction")
  )
  bsTxn = nil
  axlDBDynamicShapes(t)
  when(isFile("result.brd") deleteFile("result.brd"))
  bsLog("Saving result.brd with Allegro database checks enabled")
  unless(axlSaveDesign(?design "result.brd" ?noConfirm t)
    bsError("Could not save result.brd")
  )
  t
)

procedure(bsRun()
  let((port result)
    port = outfile("execution.log" "w")
    when(port
      fprintf(port "Native SKILL execution started\n")
      close(port)
    )
    when(isFile("result.json") deleteFile("result.json"))
    result = errset(bsMain() t)
    if(result then
      bsLog("SUCCESS result.brd saved")
      bsResult("success" "")
      axlOSExit(0)
    else
      when(bsTxn
        axlDBTransactionRollback(bsTxn)
        bsTxn = nil
      )
      when(isFile("result.brd") deleteFile("result.brd"))
      bsLog("FAILED; no successful result.brd was kept")
      bsResult("failed" "SKILL execution failed; see execution.log")
      axlOSExit(2)
    )
  )
)

bsRun()
'''


_SKILL_SESSION_SUPPORT = r'''
bsCancelled = nil
bsCommitted = nil
bsRollbackFailed = nil
bsBackupPath = __BS_BACKUP__
bsCancelPath = __BS_CANCEL__
bsFinishedPath = __BS_FINISHED__
bsStartedPath = __BS_STARTED__

procedure(bsResult(status errorText)
  let((port modified)
    port = outfile(bsResultJsonPath "w")
    unless(port bsError("Cannot write result.json"))
    modified = if(bsRollbackFailed then "null" else if(bsCommitted then "true" else "false"))
    if(equal(status "success") then
      fprintf(port "{\"status\":\"success\",\"result_brd\":\"%s\",\"execution_log\":\"%s\",\"planes_replaced\":%d,\"components_updated\":%d,\"components_missing\":%d,\"design_modified\":%s,\"recovery_brd\":\"%s\"}\n"
        bsResultBrdPath bsLogPath bsPlanes bsComponents bsMissingComponents modified bsBackupPath)
    else
      fprintf(port "{\"status\":\"%s\",\"error\":\"%s\",\"execution_log\":\"%s\",\"design_modified\":%s,\"recovery_brd\":\"%s\"}\n"
        status errorText bsLogPath modified bsBackupPath)
    )
    close(port)
  )
)

procedure(bsTouch(path text)
  let((port)
    port = outfile(path "w")
    unless(port bsError(sprintf(nil "Cannot write marker: %s" path)))
    fprintf(port "%s\n" text)
    close(port)
  )
)

procedure(bsSessionPathsFree()
  !isFile(__BS_LOG__) &&
  !isFile(__BS_RESULT_JSON__) &&
  !isFile(bsBackupPath) &&
  !isFile(bsResultBrdPath) &&
  !isFile(bsFinishedPath) &&
  !isFile(bsStartedPath)
)

procedure(bsCheckCancel()
  when(isFile(bsCancelPath)
    bsCancelled = t
    bsError("Cancellation requested")
  )
)
'''


_SKILL_SESSION_FOOTER = r'''procedure(bsMain()
  let((currentDesign)
    bsCheckCancel()
    unless(axlOKToProceed(t)
      bsError("Allegro is busy with another command or operation")
    )
    currentDesign = axlGetDrawingName()
    unless(currentDesign bsError("No current Allegro drawing is available"))
    bsMM = axlMKSConvert(1.0 "mm" car(axlDBGetDesignUnits()))
    unless(bsMM bsError("Could not convert millimeters to active BRD units"))
    bsLog(sprintf(nil "Using current open design: %s" currentDesign))
    bsValidateAll()
    bsCheckCancel()
    bsLog("Saving recovery snapshot before native modifications")
    unless(axlSaveDesign(?design bsBackupPath ?noMru t ?noConfirm t ?writeModel t)
      bsError("Could not save session-before.brd recovery snapshot")
    )
    bsCheckCancel()
    bsTxn = axlDBTransactionStart()
    unless(bsTxn bsError("Could not start Allegro database transaction"))
    bsApply()
    when(bsMissingComponents > 0
      bsError(sprintf(nil "%d component(s) could not be updated" bsMissingComponents))
    )
    bsCheckCancel()
    unless(axlDBTransactionCommit(bsTxn)
      bsError("Could not commit database transaction")
    )
    bsTxn = nil
    bsCommitted = t
    bsLog("Saving result.brd with Allegro database checks enabled")
    unless(axlSaveDesign(?design bsResultBrdPath ?noMru t ?noConfirm t)
      bsError("Could not save result.brd")
    )
    t
  )
)

procedure(bsRun()
  ; No return form is used here: return only unwinds an enclosing prog, so
  ; outside one it would signal an error instead of refusing the job cleanly.
  let((result rollback)
    if(bsSessionPathsFree() then
      bsTouch(bsStartedPath "started")
      result = errset(bsMain() t)
      if(result then
        bsLog("SUCCESS result.brd saved; Allegro session remains open")
        bsResult("success" "")
      else
        when(bsTxn
          rollback = errset(axlDBTransactionRollback(bsTxn) t)
          unless(rollback && car(rollback)
            bsRollbackFailed = t
            bsLog("ROLLBACK FAILED; design modification state is unknown; recover with session-before.brd")
          )
          bsTxn = nil
        )
        if(bsCancelled && !bsRollbackFailed then
          bsLog("CANCELLED; active transaction rolled back when possible")
          bsResult("cancelled" "Cancellation requested; session remains open")
        else
          if(bsCommitted then
            bsLog("FAILED after commit/save; current design remains modified; recover with session-before.brd")
          else
            bsLog("FAILED before commit; active transaction rolled back when possible; keep session-before.brd for recovery")
          )
          bsResult("failed" "SKILL execution failed; see execution.log and session-before.brd")
        )
      )
      bsTouch(bsFinishedPath "finished")
      bsSessionBusy = nil
    else
      printf("BRD-SPD session job refused: one or more output paths already exist.\n")
      bsSessionBusy = nil
    )
  )
)

bsRun()
'''


def _session_paths(output_dir: Path) -> dict[str, str]:
    root = output_dir.resolve()
    return {
        "log": (root / "execution.log").as_posix(),
        "result_json": (root / "result.json").as_posix(),
        "backup": (root / "session-before.brd").as_posix(),
        "cancel": (root / "cancel.flag").as_posix(),
        "finished": (root / "finished.flag").as_posix(),
        "started": (root / "execution.started").as_posix(),
        "result_brd": (root / "result.brd").as_posix(),
    }


def _session_header(paths: dict[str, str]) -> str:
    header = _SKILL_HEADER.replace(
        'bsLogPath = "execution.log"', f"bsLogPath = {_skill_string(paths['log'])}"
    )
    header = header.replace(
        'bsResultJsonPath = "result.json"',
        f"bsResultJsonPath = {_skill_string(paths['result_json'])}",
    )
    header = header.replace(
        'bsResultBrdPath = "result.brd"',
        f"bsResultBrdPath = {_skill_string(paths['result_brd'])}",
    )
    header = header.replace(
        "; base.brd must be supplied in this directory by the caller.",
        "; Existing-session mode: operate on the current open drawing and keep Allegro open.",
    )
    support = _SKILL_SESSION_SUPPORT
    for token, key in (
        ("__BS_BACKUP__", "backup"),
        ("__BS_CANCEL__", "cancel"),
        ("__BS_FINISHED__", "finished"),
        ("__BS_STARTED__", "started"),
        ("__BS_LOG__", "log"),
        ("__BS_RESULT_JSON__", "result_json"),
    ):
        support = support.replace(token, _skill_string(paths[key]))
    return header + support


def _session_busy_prefix(paths: dict[str, str]) -> str:
    values = {key: _skill_string(value) for key, value in paths.items()}
    return f'''if(boundp('bsSessionBusy) && bsSessionBusy then
  let((port status message collision)
    collision = isFile({values["log"]}) ||
      isFile({values["result_json"]}) ||
      isFile({values["backup"]}) ||
      isFile({values["result_brd"]}) ||
      isFile({values["finished"]}) ||
      isFile({values["started"]})
    if(collision then
      printf("BRD-SPD session job refused: output paths already exist.\\n")
    else
      port = outfile({values["started"]} "w")
      when(port fprintf(port "started\\n") close(port))
      if(isFile({values["cancel"]}) then
        status = "cancelled"
        message = "Cancellation requested before execution"
      else
        status = "failed"
        message = "Another BRD-SPD session job is active"
      )
      port = outfile({values["log"]} "w")
      when(port fprintf(port "%s\\n" message) close(port))
      port = outfile({values["result_json"]} "w")
      when(port
        fprintf(port "{{\\\"status\\\":\\\"%s\\\",\\\"error\\\":\\\"%s\\\",\\\"execution_log\\\":\\\"%s\\\",\\\"design_modified\\\":false,\\\"recovery_brd\\\":\\\"%s\\\"}}\\n"
          status message {values["log"]} {values["backup"]})
        close(port)
      )
      port = outfile({values["finished"]} "w")
      when(port fprintf(port "finished\\n") close(port))
    )
  )
else
  progn(
    bsSessionBusy = t
'''


_SKILL_SESSION_WRAPPER_SUFFIX = "  )\n)\n"


def _selected_layer(requested: set[str] | None, original: str, native: str) -> bool:
    return requested is None or original.casefold() in requested or native.casefold() in requested


def _selected_positives(db, section: str, selected_nets: set[str] | None) -> list[tuple]:
    return [
        row
        for row in db.execute(
            "SELECT rowid,net,kind,data FROM shapes WHERE section=? AND polarity='+'", (section,)
        )
        if row[1] and (selected_nets is None or row[1].casefold() in selected_nets)
    ]


def _associate_voids(
    db, section: str, selected_nets: set[str] | None, report: _Report, associated: set | None = None
):
    """Attach every negative record to the positives it removes copper from.

    Negatives are never filtered by net before the search: a netless void may
    belong to any emitted positive, a void with a net only to a positive on the
    same net.  A void that no selected positive contains is dropped, and counted,
    only when its own net is not part of the selection; a negative on net A can
    never remove copper from net B, so foreign copper around it proves nothing.
    """
    db.execute(
        "CREATE TEMP TABLE IF NOT EXISTS native_holes(section TEXT, parent INTEGER, child INTEGER)"
    )
    if associated is not None and section in associated:
        # The same section can be patched onto several layers.  Associate it
        # once so the SPD record counts are not multiplied by the layer count.
        return [row[0] for row in _selected_positives(db, section, selected_nets)]
    db.execute("DELETE FROM native_holes WHERE section=?", (section,))
    positives, geometries, circles, nets = [], [], [], []
    for rowid, net, kind, encoded in _selected_positives(db, section, selected_nets):
        geometry, data = _shape(encoded, kind)
        if not geometry.is_valid or geometry.is_empty:
            raise ValueError(f"Invalid positive plane geometry in {section!r}, shape row {rowid}")
        prepare(geometry)
        positives.append(rowid)
        geometries.append(geometry)
        circles.append(data if kind == "Circle" else None)
        nets.append(net)
    tree = STRtree(geometries) if geometries else None
    for rowid, net, kind, encoded, line in db.execute(
        "SELECT rowid,net,kind,data,line FROM shapes WHERE section=? AND polarity='-'", (section,)
    ):
        hole, data = _shape(encoded, kind)
        if not hole.is_valid or hole.is_empty:
            raise ValueError(f"Invalid plane void geometry in {section!r}, shape row {rowid}")
        hole_circle = data if kind == "Circle" else None
        parents, parent_nets, crossing = [], [], []
        if tree is not None:
            for index in tree.query(hole):
                if net and nets[index] != net:
                    continue
                if _contains(geometries[index], circles[index], hole, hole_circle, data):
                    parents.append(positives[index])
                    parent_nets.append(nets[index])
                elif _overlaps(geometries[index], circles[index], hole, hole_circle):
                    crossing.append(positives[index])
        if crossing:
            rows = ", ".join(str(row) for row in sorted(set(parents + crossing)))
            if parents or len(crossing) > 1:
                raise ValueError(
                    f"line {line}: plane void in {section!r}, shape row {rowid} on net {net!r}: "
                    f"void spans several overlapping same-net positive shapes (rows {rows}) "
                    f"without being inside one of them; split the void or merge the shapes in the SPD"
                )
            raise ValueError(
                f"line {line}: plane void in {section!r}, shape row {rowid} on net {net!r} "
                f"overlaps positive shape row {crossing[0]} without being contained in it"
            )
        if not parents:
            if not net or (selected_nets is not None and net.casefold() not in selected_nets):
                report.warn(
                    "NATIVE_VOID_OUTSIDE_SELECTION",
                    f"{section!r}, shape row {rowid}: void on net {net!r} has no containing "
                    f"positive shape in the selection and is not emitted",
                    line,
                )
                report.counts["native_voids_outside_selection"] += 1
                continue
            raise ValueError(
                f"line {line}: plane void in {section!r}, shape row {rowid} has no unique "
                f"positive parent on net {net!r}"
            )
        if len(set(parent_nets)) > 1:
            # Different nets sharing copper on one layer is a short, not a void.
            pairs = ", ".join(
                f"row {parent} ({parent_net})"
                for parent, parent_net in sorted(zip(parents, parent_nets))
            )
            raise ValueError(
                f"line {line}: plane void in {section!r}, shape row {rowid} is contained in "
                f"positive shapes of different nets ({pairs}); overlapping copper of different "
                f"nets on one layer cannot be voided safely"
            )
        if len(parents) > 1:
            # SPD removes copper from every same-net positive it overlaps.
            report.warn(
                "NATIVE_VOID_MULTIPLE_PARENTS",
                f"{section!r}, shape row {rowid}: void is contained in {len(parents)} positive "
                f"shapes and is emitted into each of them",
                line,
            )
            report.counts["native_voids_multiple_parents"] += 1
        if any(parent > rowid for parent in parents):
            report.warn(
                "NATIVE_VOID_ORDER_FALLBACK",
                f"{section!r}, shape row {rowid}: a containing positive shape occurs later in the file",
                line,
            )
            report.counts["native_voids_before_parent"] += 1
        db.executemany(
            "INSERT INTO native_holes VALUES (?,?,?)",
            [(section, parent, rowid) for parent in parents],
        )
        report.counts["native_voids"] += 1
        report.counts["native_void_emissions"] += len(parents)
    db.execute("CREATE INDEX IF NOT EXISTS native_holes_parent ON native_holes(parent)")
    if associated is not None:
        associated.add(section)
    return positives


def _write_plane_calls(
    handle, db, section, layer, selected_nets, report, *, session_mode=False, associated=None
):
    positives = _associate_voids(db, section, selected_nets, report, associated)
    for rowid in positives:
        if session_mode:
            handle.write("    bsCheckCancel()\n")
        net, kind, encoded = db.execute(
            "SELECT net,kind,data FROM shapes WHERE rowid=?", (rowid,)
        ).fetchone()
        data = json.loads(encoded)
        if kind == "Circle":
            handle.write(
                f"    bsBeginCircle({_skill_string(layer)} {_skill_string(net)} "
                f"{_num(data[0])} {_num(data[1])} {_num(data[2])})\n"
            )
        else:
            handle.write(
                f"    bsBeginPolygon({_skill_string(layer)} {_skill_string(net)} {_point_list(data)})\n"
            )
        for child_kind, child_data in db.execute(
            "SELECT s.kind,s.data FROM native_holes h JOIN shapes s ON s.rowid=h.child "
            "WHERE h.parent=? ORDER BY s.rowid", (rowid,)
        ):
            values = json.loads(child_data)
            if child_kind == "Circle":
                handle.write(
                    f"    bsCircleVoid({_num(values[0])} {_num(values[1])} {_num(values[2])})\n"
                )
            else:
                handle.write(f"    bsPolygonVoid({_point_list(values)})\n")
        handle.write("    bsEndPlane()\n")
        report.counts["native_plane_shapes"] += 1


def _write_reports(output_dir: Path, status: str, report: _Report, details: dict) -> dict:
    report_path = output_dir / "generation.report.json"
    log_path = output_dir / "generation.log"
    payload = {
        "status": status,
        "backend": "allegro-24.1-skill",
        "execution_verified": False,
        "counts": dict(report.counts),
        "warnings": report.warnings,
        **details,
    }
    report_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = [
        f"Native SKILL bundle generation: {status}",
        "Execution verified: false (requires Allegro 24.1 runtime)",
        "",
        "COUNTS",
        *[f"{key}: {value}" for key, value in sorted(report.counts.items())],
        "",
        "WARNINGS / LIMITS",
    ]
    for code, item in report.warnings.items():
        lines.append(f"[{code}] occurrences={item['count']}")
        lines.extend(f"  line={sample['line']}: {sample['message']}" for sample in item["samples"])
    if details.get("selected_pairs"):
        lines.extend(["", "SELECTED LAYER/NET PAIRS"])
        lines.extend(
            f"{item['layer']} / {item['net']}" for item in details["selected_pairs"]
        )
    if details.get("error"):
        lines.extend(["", "ERROR: " + details["error"]])
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {
        "status": status,
        "bundle_path": str(output_dir.resolve()),
        "report_path": str(report_path.resolve()),
        "log_path": str(log_path.resolve()),
        "counts": dict(report.counts),
        "warnings": report.warnings,
    }


def generate_bundle(
    source: Path,
    output_dir: Path,
    *,
    layers: list[str] | None = None,
    nets: list[str] | None = None,
    update_components: bool = False,
    session_mode: bool = False,
    progress=None,
) -> dict:
    """Create a conservative, unexecuted Allegro SKILL update bundle."""
    source, output_dir = Path(source), Path(output_dir)
    if not source.is_file():
        raise FileNotFoundError(source)
    if output_dir.exists():
        raise FileExistsError(f"Native bundle directory already exists: {output_dir}")
    output_dir.mkdir(parents=True)
    report = _Report()
    database = output_dir / ".generation.sqlite"
    requested_layers = {str(item).casefold() for item in layers} if layers is not None else None
    requested_nets = {str(item).casefold() for item in nets} if nets is not None else None
    try:
        if progress:
            progress("Native bundle: parsing SPD")
        metadata = parse_spd(source, database, report, progress)
        db = sqlite3.connect(database)
        try:
            conductor_layers = {
                layer["name"] for layer in metadata["layers"] if layer["kind"] == "CONDUCTOR"
            }
            conductor_order = [
                layer["name"] for layer in metadata["layers"] if layer["kind"] == "CONDUCTOR"
            ]
            # Two stackup layers that become the same ETCH layer would silently
            # be merged into one native layer, as the IPC path already refuses.
            native_names: dict[str, str] = {}
            for original in conductor_order:
                native = _native_layer(original)
                if native_names.setdefault(native, original) != original:
                    raise ValueError(
                        "Layer names collide after removing Signal$/Plane$ prefixes: "
                        f"{native_names[native]!r} and {original!r} both map to ETCH/{native}"
                    )
            sections = []
            found_layers, found_nets, pairs = set(), set(), set()
            mapped_sections = set(metadata["shape_layers"])
            for section, count in db.execute(
                "SELECT section,COUNT(*) FROM shapes GROUP BY section"
            ):
                if section not in mapped_sections:
                    report.warn(
                        "NATIVE_UNMAPPED_SHAPE_SECTION",
                        f"Shape section {section!r} has no Patch... Layer mapping; {count} records are not emitted",
                    )
                    report.counts["unsupported_unmapped_shapes"] += count
            for section, section_layers in metadata["shape_layers"].items():
                # One .Shape section can be patched onto several layers; every
                # patched layer gets its own pair and its own shape emission.
                for original in section_layers:
                    if original not in conductor_layers:
                        shape_count = db.execute(
                            "SELECT COUNT(*) FROM shapes WHERE section=?", (section,)
                        ).fetchone()[0]
                        if shape_count:
                            report.warn(
                                "NATIVE_NONCONDUCTOR_SHAPES_NOT_EMITTED",
                                f"{section!r} maps to non-conductor layer {original!r}; {shape_count} records are not emitted",
                            )
                            report.counts["unsupported_nonconductor_shapes"] += shape_count
                        continue
                    native = _native_layer(original)
                    if not _selected_layer(requested_layers, original, native):
                        continue
                    no_net_count = db.execute(
                        "SELECT COUNT(*) FROM shapes WHERE section=? AND polarity='+' AND net=''", (section,)
                    ).fetchone()[0]
                    if no_net_count:
                        raise ValueError(
                            f"Native plane section {section!r} contains {no_net_count} positive shapes without a net"
                        )
                    positive_nets = {
                        row[0] for row in db.execute(
                            "SELECT DISTINCT net FROM shapes WHERE section=? AND polarity='+' AND net!=''", (section,)
                        )
                        if requested_nets is None or row[0].casefold() in requested_nets
                    }
                    if positive_nets:
                        found_layers.update((original.casefold(), native.casefold()))
                        sections.append((section, original, native))
                        for net in positive_nets:
                            pairs.add((native, net))
                            found_nets.add(net.casefold())
            missing_layers = sorted(requested_layers - found_layers) if requested_layers is not None else []
            missing_nets = sorted(requested_nets - found_nets) if requested_nets is not None else []
            if missing_layers or missing_nets or not pairs:
                missing = []
                if missing_layers:
                    missing.append("layers=" + ",".join(missing_layers))
                if missing_nets:
                    missing.append("nets=" + ",".join(missing_nets))
                if not pairs:
                    missing.append("no positive plane geometry selected")
                raise ValueError("Native selection did not resolve safely: " + "; ".join(missing))

            report.warn(
                "NATIVE_EXECUTION_NOT_VERIFIED",
                "SKILL was generated but must be executed and checked by Allegro 24.1",
            )
            report.warn(
                "NATIVE_PLANE_DELETE_SCOPE",
                "Each selected ETCH/BOUNDARY layer+net shape set is replaced; review shape-based routing on those pairs",
            )
            if session_mode:
                report.warn(
                    "NATIVE_EXISTING_SESSION_MODE",
                    "The selected Allegro process current open design is the source; execution first writes session-before.brd",
                )
                report.warn(
                    "NATIVE_SESSION_DYNAMIC_REPOUR_DEFERRED",
                    "Session mode does not globally repour unrelated dynamic shapes; review or update them in Allegro after the scoped result",
                )
            report.warn(
                "NATIVE_DYNAMIC_PLANE_RULES_NOT_RESTORED",
                "Selected planes become static copper with explicit voids. Original dynamic boundaries, "
                "clearance/thermal/repour parameters and editable shape intent cannot be recovered from SPD; "
                "unselected base-board objects and global constraints are retained.",
            )
            for key, code, label in (
                ("traces", "NATIVE_TRACES_PRESERVED", "SPD trace differences are not applied"),
                ("vias", "NATIVE_VIAS_PRESERVED", "SPD via differences are not applied"),
            ):
                count = metadata["counts"].get(key, 0)
                if count:
                    report.warn(code, f"{label}; base BRD objects remain ({count} SPD records)")
                    report.counts[f"unsupported_{key}"] = count
            component_count = len(metadata["components"])
            if component_count and not update_components:
                report.warn(
                    "NATIVE_COMPONENTS_PRESERVED",
                    f"Component placement updates disabled; base BRD placements remain ({component_count} SPD records)",
                )
            elif update_components:
                report.warn(
                    "NATIVE_COMPONENT_SET_NOT_SYNCHRONIZED",
                    "Only existing placed refdes are moved/rotated; missing, new, deleted, or side-changed components are not synchronized",
                )

            design_path = output_dir / "design.il"
            runtime_paths = _session_paths(output_dir) if session_mode else None
            with design_path.open("w", encoding="utf-8", newline="\n") as skill:
                if session_mode:
                    skill.write(_session_busy_prefix(runtime_paths))
                    skill.write(_session_header(runtime_paths))
                else:
                    skill.write(_SKILL_HEADER)
                skill.write("\nprocedure(bsValidateAll()\n")
                for layer, net in sorted(pairs, key=lambda item: (item[0].casefold(), item[1].casefold())):
                    skill.write(f"  bsValidate({_skill_string(layer)} {_skill_string(net)})\n")
                skill.write("  t\n)\n\nprocedure(bsApply()\n  progn(\n")
                for layer, net in sorted(pairs, key=lambda item: (item[0].casefold(), item[1].casefold())):
                    if session_mode:
                        skill.write("    bsCheckCancel()\n")
                    skill.write(f"    bsDeletePlane({_skill_string(layer)} {_skill_string(net)})\n")
                associated: set[str] = set()
                for index, (section, _original, native) in enumerate(sections, 1):
                    if progress:
                        progress(f"Native bundle: plane section {index}/{len(sections)}")
                    _write_plane_calls(
                        skill,
                        db,
                        section,
                        native,
                        requested_nets,
                        report,
                        session_mode=session_mode,
                        associated=associated,
                    )
                if update_components:
                    if len(conductor_order) < 2:
                        raise ValueError("Component side validation requires distinct outer conductor layers")
                    top_layer, bottom_layer = conductor_order[0], conductor_order[-1]
                    for refdes, component in sorted(metadata["components"].items()):
                        component_layer = component.get("layer")
                        if component_layer == top_layer:
                            expected_mirrored = "nil"
                        elif component_layer == bottom_layer:
                            expected_mirrored = "t"
                        else:
                            raise ValueError(
                                f"Component {refdes!r} has missing or unsupported placement layer {component_layer!r}"
                            )
                        if session_mode:
                            skill.write("    bsCheckCancel()\n")
                        skill.write(
                            f"    bsUpdateComponent({_skill_string(refdes)} {_num(component['x'])} "
                            f"{_num(component['y'])} {_num(component.get('rotation', 0.0))} "
                            f"{expected_mirrored})\n"
                        )
                    report.counts["component_updates_requested"] = component_count
                skill.write("    t\n  )\n)\n\n")
                skill.write(_SKILL_SESSION_FOOTER if session_mode else _SKILL_FOOTER)
                if session_mode:
                    skill.write(_SKILL_SESSION_WRAPPER_SUFFIX)

            if session_mode:
                from .process_target import _encode_command
                dispatch_command = f"skill load({_skill_string(design_path.resolve().as_posix())})\n"
                _encode_command(dispatch_command.rstrip("\n"))
                (output_dir / "run.scr").write_text(dispatch_command, encoding="utf-8")
            else:
                dispatch_command = None
                (output_dir / "run.scr").write_text(
                    'skill load("design.il")\nexit\n', encoding="ascii"
                )
            manifest = {
                "schema_version": 1,
                "backend": "allegro-24.1-skill",
                "generated_utc": datetime.now(timezone.utc).isoformat(),
                "status": "generated_unverified",
                "base_brd": "current_open_design" if session_mode else "caller_supplied",
                "result_brd": runtime_paths["result_brd"] if session_mode else "result.brd",
                "execution_result": runtime_paths["result_json"] if session_mode else "result.json",
                "plane_mode": "replace_static_etch_shapes",
                "session_mode": bool(session_mode),
                "selected_pairs": [{"layer": layer, "net": net} for layer, net in sorted(pairs)],
                "update_existing_components": bool(update_components),
                "unsupported": ["trace_deltas", "via_deltas", "component_add_delete", "component_side_change"],
            }
            if session_mode:
                manifest.update(
                    {
                        "dispatch_command": dispatch_command.rstrip("\n"),
                        "recovery_brd": runtime_paths["backup"],
                        "cancel_flag": runtime_paths["cancel"],
                        "started_marker": runtime_paths["started"],
                        "finished_marker": runtime_paths["finished"],
                    }
                )
            (output_dir / "manifest.json").write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
            )
            report.counts["native_layer_net_pairs"] = len(pairs)
            report.counts["native_sections"] = len(sections)
            selected_pairs = [
                {"layer": layer, "net": net} for layer, net in sorted(pairs)
            ]
            return _write_reports(
                output_dir,
                "generated_unverified",
                report,
                {
                    "manifest_path": str((output_dir / "manifest.json").resolve()),
                    "selected_pairs": selected_pairs,
                    "update_existing_components": bool(update_components),
                    "session_mode": bool(session_mode),
                },
            )
        finally:
            db.close()
    except Exception as exc:
        report.warn("NATIVE_BUNDLE_GENERATION_FAILED", str(exc))
        for filename in ("design.il", "run.scr", "manifest.json"):
            candidate = output_dir / filename
            if candidate.exists():
                candidate.unlink()
        _write_reports(output_dir, "failed", report, {"error": str(exc)})
        raise
    finally:
        if database.exists():
            database.unlink()
        journal = database.with_name(database.name + "-journal")
        if journal.exists():
            journal.unlink()
