"""Generate an Allegro 24.1 SKILL bundle for conservative native plane updates."""
from __future__ import annotations

import json
import math
import sqlite3
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from shapely import prepare
from shapely.geometry import Point, Polygon
from shapely.strtree import STRtree

from .spd import parse_spd


class _Report:
    def __init__(self):
        self.counts = Counter()
        self.warnings: dict[str, dict] = {}

    def warn(self, code, message, line=None):
        item = self.warnings.setdefault(code, {"count": 0, "samples": []})
        item["count"] += 1
        if len(item["samples"]) < 5:
            item["samples"].append({"line": line, "message": str(message)})


def _skill_string(value: str) -> str:
    """JSON string quoting is compatible with SKILL for these UTF-8 strings."""
    return json.dumps(str(value), ensure_ascii=False)


def _num(value: float) -> str:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError("Non-finite native geometry")
    return format(value, ".12g")


def _native_layer(name: str) -> str:
    for prefix in ("Signal$", "Plane$"):
        if name.startswith(prefix):
            return name[len(prefix) :]
    return name


def _shape(encoded: str, kind: str):
    data = json.loads(encoded)
    if kind == "Circle":
        return Point(data[:2]).buffer(data[2], quad_segs=32), data
    return Polygon(list(zip(data[::2], data[1::2]))), data


def _point_list(data: list[float]) -> str:
    points = list(zip(data[::2], data[1::2]))
    if points[-1] != points[0]:
        points.append(points[0])
    return "list(" + " ".join(f"bsP({_num(x)} {_num(y)})" for x, y in points) + ")"


_SKILL_HEADER = r'''; Generated by BRD-SPD-IPC2581. Requires Allegro X PCB Editor 24.1.
; base.brd must be supplied in this directory by the caller.
bsTxn = nil
bsMM = nil
bsShape = nil
bsPlanes = 0
bsComponents = 0
bsMissingComponents = 0

procedure(bsLog(msg)
  let((port)
    port = outfile("execution.log" "a")
    when(port
      fprintf(port "%s\n" msg)
      close(port)
    )
  )
)

procedure(bsError(message)
  bsLog(strcat("ERROR " message))
  error(message)
)

procedure(bsResult(status errorText)
  let((port)
    port = outfile("result.json" "w")
    unless(port bsError("Cannot write result.json"))
    if(equal(status "success") then
      fprintf(port "{\"status\":\"success\",\"result_brd\":\"result.brd\",\"execution_log\":\"execution.log\",\"planes_replaced\":%d,\"components_updated\":%d,\"components_missing\":%d}\n"
        bsPlanes bsComponents bsMissingComponents)
    else
      fprintf(port "{\"status\":\"failed\",\"error\":\"%s\",\"execution_log\":\"execution.log\"}\n" errorText)
    )
    close(port)
  )
)

procedure(bsP(x y) list(x * bsMM y * bsMM))
procedure(bsL(value) value * bsMM)

procedure(bsFindNet(netName)
  car(axlSelectByName("NET" netName))
)

procedure(bsValidate(layerName netName)
  unless(axlGetParam(strcat("paramLayerGroup:ETCH/paramLayer:" layerName))
    bsError(sprintf(nil "Missing ETCH layer: %s" layerName))
  )
  unless(bsFindNet(netName)
    bsError(sprintf(nil "Missing net: %s" netName))
  )
)

procedure(bsDeletePlane(layerName netName)
  let((shape)
    foreach(shape copy(axlDBGetShapes(strcat("BOUNDARY/" layerName)))
      when(shape->net && equal(shape->net->name netName)
        unless(axlDeleteObject(shape)
          bsError(sprintf(nil "Could not delete dynamic plane %s/%s" layerName netName))
        )
      )
    )
    foreach(shape copy(axlDBGetShapes(strcat("ETCH/" layerName)))
      when(shape->net && equal(shape->net->name netName) && null(shape->shapeBoundary)
        unless(axlDeleteObject(shape)
          bsError(sprintf(nil "Could not delete static plane %s/%s" layerName netName))
        )
      )
    )
  )
)

procedure(bsBeginPolygon(layerName netName points)
  let((path)
    path = axlPathStart(points)
    unless(path bsError("Could not construct polygon path"))
    bsShape = axlDBCreateOpenShape(path t strcat("ETCH/" layerName) netName)
    unless(bsShape bsError(sprintf(nil "Could not create plane %s/%s" layerName netName)))
  )
)

procedure(bsBeginCircle(layerName netName x y radius)
  let((path)
    path = axlPathStartCircle(list(bsP(x y) bsL(radius)) 0.0)
    unless(path bsError("Could not construct circular plane path"))
    bsShape = axlDBCreateOpenShape(path t strcat("ETCH/" layerName) netName)
    unless(bsShape bsError(sprintf(nil "Could not create circular plane %s/%s" layerName netName)))
  )
)

procedure(bsPolygonVoid(points)
  let((path)
    path = axlPathStart(points)
    unless(path && axlDBCreateVoid(bsShape path)
      bsError("Could not create polygon plane void")
    )
  )
)

procedure(bsCircleVoid(x y radius)
  unless(axlDBCreateVoidCircle(bsShape list(bsP(x y) bsL(radius)) 0.0)
    bsError("Could not create circular plane void")
  )
)

procedure(bsEndPlane()
  unless(axlDBCreateCloseShape(bsShape)
    bsError("Could not close/fill plane shape")
  )
  bsShape = nil
  bsPlanes = bsPlanes + 1
  when(mod(bsPlanes 100) == 0
    bsLog(sprintf(nil "Created %d plane shapes" bsPlanes))
  )
)

procedure(bsUpdateComponent(refdes x y rotation expectedMirrored)
  let((component symbol actualMirrored dx dy da moved)
    component = car(axlSelectByName("COMPREFDES" refdes))
    if(null(component) || null(component->symbol) then
      bsMissingComponents = bsMissingComponents + 1
      bsLog(sprintf(nil "UNSUPPORTED missing/unplaced component: %s" refdes))
      bsError(sprintf(nil "Cannot update missing/unplaced component: %s" refdes))
    else
      symbol = component->symbol
      actualMirrored = symbol->mirrorType && !equal(symbol->mirrorType "NO")
      unless(equal(actualMirrored expectedMirrored)
        bsError(sprintf(nil "Component side differs from SPD: %s" refdes))
      )
      dx = bsL(x) - xCoord(symbol->xy)
      dy = bsL(y) - yCoord(symbol->xy)
      da = rotation - symbol->rotation
      moved = axlTransformObject(symbol ?move list(dx dy) ?angle da ?allOrNone t)
      unless(moved bsError(sprintf(nil "Could not update component: %s" refdes)))
      bsComponents = bsComponents + 1
    )
  )
)
'''


_SKILL_FOOTER = r'''procedure(bsMain()
  unless(isFile("base.brd") bsError("base.brd is missing"))
  unless(axlOpenDesignForBatch("base.brd" "wf") bsError("Could not open base.brd"))
  bsMM = axlMKSConvert(1.0 "mm" car(axlDBGetDesignUnits()))
  unless(bsMM bsError("Could not convert millimeters to active BRD units"))
  bsLog("Opened base.brd; validating requested layers and nets")
  bsValidateAll()
  bsTxn = axlDBTransactionStart()
  unless(bsTxn bsError("Could not start Allegro database transaction"))
  bsApply()
  unless(axlDBTransactionCommit(bsTxn)
    bsError("Could not commit database transaction")
  )
  bsTxn = nil
  axlDBDynamicShapes(t)
  when(isFile("result.brd") deleteFile("result.brd"))
  bsLog("Saving result.brd with Allegro database checks enabled")
  unless(axlSaveDesign(?design "result.brd" ?noConfirm t)
    bsError("Could not save result.brd")
  )
  t
)

procedure(bsRun()
  let((port result)
    port = outfile("execution.log" "w")
    when(port
      fprintf(port "Native SKILL execution started\n")
      close(port)
    )
    when(isFile("result.json") deleteFile("result.json"))
    result = errset(bsMain() t)
    if(result then
      bsLog("SUCCESS result.brd saved")
      bsResult("success" "")
      axlOSExit(0)
    else
      when(bsTxn
        axlDBTransactionRollback(bsTxn)
        bsTxn = nil
      )
      when(isFile("result.brd") deleteFile("result.brd"))
      bsLog("FAILED; no successful result.brd was kept")
      bsResult("failed" "SKILL execution failed; see execution.log")
      axlOSExit(2)
    )
  )
)

bsRun()
'''


def _selected_layer(requested: set[str] | None, original: str, native: str) -> bool:
    return requested is None or original.casefold() in requested or native.casefold() in requested


def _associate_voids(db, section: str, selected_nets: set[str] | None, report: _Report):
    db.execute("CREATE TEMP TABLE IF NOT EXISTS native_holes(parent INTEGER, child INTEGER)")
    db.execute("DELETE FROM native_holes")
    positives, geometries, nets, valid = [], [], [], []
    for rowid, net, kind, encoded in db.execute(
        "SELECT rowid,net,kind,data FROM shapes WHERE section=? AND polarity='+'", (section,)
    ):
        if not net or (selected_nets is not None and net.casefold() not in selected_nets):
            continue
        geometry, _ = _shape(encoded, kind)
        ok = geometry.is_valid and not geometry.is_empty
        if not ok:
            raise ValueError(f"Invalid positive plane geometry in {section!r}, shape row {rowid}")
        prepare(geometry)
        positives.append(rowid)
        geometries.append(geometry)
        nets.append(net)
        valid.append(ok)
    tree = STRtree(geometries) if geometries else None
    for rowid, net, kind, encoded, line in db.execute(
        "SELECT rowid,net,kind,data,line FROM shapes WHERE section=? AND polarity='-'", (section,)
    ):
        if not net or (selected_nets is not None and net.casefold() not in selected_nets):
            continue
        hole, data = _shape(encoded, kind)
        if not hole.is_valid or hole.is_empty:
            raise ValueError(f"Invalid plane void geometry in {section!r}, shape row {rowid}")
        parents = []
        if tree is not None:
            for index in tree.query(hole):
                if nets[index] != net or not valid[index]:
                    continue
                outer = geometries[index]
                if kind == "Circle":
                    center = Point(data[:2])
                    contained = outer.covers(center) and outer.boundary.distance(center) + 1e-9 >= data[2]
                else:
                    contained = outer.covers(hole)
                if contained:
                    parents.append(positives[index])
        preceding = [parent for parent in parents if parent < rowid]
        parent = max(preceding) if preceding else (parents[0] if len(parents) == 1 else None)
        if parent is None:
            raise ValueError(
                f"line {line}: plane void in {section!r}, shape row {rowid} has no unique "
                f"positive parent on net {net!r}"
            )
        db.execute("INSERT INTO native_holes VALUES (?,?)", (parent, rowid))
        report.counts["native_voids"] += 1
    db.execute("CREATE INDEX IF NOT EXISTS native_holes_parent ON native_holes(parent)")
    return positives


def _write_plane_calls(handle, db, section, layer, selected_nets, report):
    positives = _associate_voids(db, section, selected_nets, report)
    for rowid in positives:
        net, kind, encoded = db.execute(
            "SELECT net,kind,data FROM shapes WHERE rowid=?", (rowid,)
        ).fetchone()
        data = json.loads(encoded)
        if kind == "Circle":
            handle.write(
                f"    bsBeginCircle({_skill_string(layer)} {_skill_string(net)} "
                f"{_num(data[0])} {_num(data[1])} {_num(data[2])})\n"
            )
        else:
            handle.write(
                f"    bsBeginPolygon({_skill_string(layer)} {_skill_string(net)} {_point_list(data)})\n"
            )
        for child_kind, child_data in db.execute(
            "SELECT s.kind,s.data FROM native_holes h JOIN shapes s ON s.rowid=h.child "
            "WHERE h.parent=? ORDER BY s.rowid", (rowid,)
        ):
            values = json.loads(child_data)
            if child_kind == "Circle":
                handle.write(
                    f"    bsCircleVoid({_num(values[0])} {_num(values[1])} {_num(values[2])})\n"
                )
            else:
                handle.write(f"    bsPolygonVoid({_point_list(values)})\n")
        handle.write("    bsEndPlane()\n")
        report.counts["native_plane_shapes"] += 1


def _write_reports(output_dir: Path, status: str, report: _Report, details: dict) -> dict:
    report_path = output_dir / "generation.report.json"
    log_path = output_dir / "generation.log"
    payload = {
        "status": status,
        "backend": "allegro-24.1-skill",
        "execution_verified": False,
        "counts": dict(report.counts),
        "warnings": report.warnings,
        **details,
    }
    report_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = [
        f"Native SKILL bundle generation: {status}",
        "Execution verified: false (requires Allegro 24.1 runtime)",
        "",
        "COUNTS",
        *[f"{key}: {value}" for key, value in sorted(report.counts.items())],
        "",
        "WARNINGS / LIMITS",
    ]
    for code, item in report.warnings.items():
        lines.append(f"[{code}] occurrences={item['count']}")
        lines.extend(f"  line={sample['line']}: {sample['message']}" for sample in item["samples"])
    if details.get("selected_pairs"):
        lines.extend(["", "SELECTED LAYER/NET PAIRS"])
        lines.extend(
            f"{item['layer']} / {item['net']}" for item in details["selected_pairs"]
        )
    if details.get("error"):
        lines.extend(["", "ERROR: " + details["error"]])
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {
        "status": status,
        "bundle_path": str(output_dir.resolve()),
        "report_path": str(report_path.resolve()),
        "log_path": str(log_path.resolve()),
        "counts": dict(report.counts),
        "warnings": report.warnings,
    }


def generate_bundle(
    source: Path,
    output_dir: Path,
    *,
    layers: list[str] | None = None,
    nets: list[str] | None = None,
    update_components: bool = False,
    progress=None,
) -> dict:
    """Create a conservative, unexecuted Allegro SKILL update bundle."""
    source, output_dir = Path(source), Path(output_dir)
    if not source.is_file():
        raise FileNotFoundError(source)
    if output_dir.exists():
        raise FileExistsError(f"Native bundle directory already exists: {output_dir}")
    output_dir.mkdir(parents=True)
    report = _Report()
    database = output_dir / ".generation.sqlite"
    requested_layers = {str(item).casefold() for item in layers} if layers is not None else None
    requested_nets = {str(item).casefold() for item in nets} if nets is not None else None
    try:
        if progress:
            progress("Native bundle: parsing SPD")
        metadata = parse_spd(source, database, report, progress)
        db = sqlite3.connect(database)
        try:
            conductor_layers = {
                layer["name"] for layer in metadata["layers"] if layer["kind"] == "CONDUCTOR"
            }
            conductor_order = [
                layer["name"] for layer in metadata["layers"] if layer["kind"] == "CONDUCTOR"
            ]
            sections = []
            found_layers, found_nets, pairs = set(), set(), set()
            mapped_sections = set(metadata["shape_layers"])
            for section, count in db.execute(
                "SELECT section,COUNT(*) FROM shapes GROUP BY section"
            ):
                if section not in mapped_sections:
                    report.warn(
                        "NATIVE_UNMAPPED_SHAPE_SECTION",
                        f"Shape section {section!r} has no Patch... Layer mapping; {count} records are not emitted",
                    )
                    report.counts["unsupported_unmapped_shapes"] += count
            for section, original in metadata["shape_layers"].items():
                if original not in conductor_layers:
                    shape_count = db.execute(
                        "SELECT COUNT(*) FROM shapes WHERE section=?", (section,)
                    ).fetchone()[0]
                    if shape_count:
                        report.warn(
                            "NATIVE_NONCONDUCTOR_SHAPES_NOT_EMITTED",
                            f"{section!r} maps to non-conductor layer {original!r}; {shape_count} records are not emitted",
                        )
                        report.counts["unsupported_nonconductor_shapes"] += shape_count
                    continue
                native = _native_layer(original)
                if not _selected_layer(requested_layers, original, native):
                    continue
                no_net_count = db.execute(
                    "SELECT COUNT(*) FROM shapes WHERE section=? AND polarity='+' AND net=''", (section,)
                ).fetchone()[0]
                if no_net_count:
                    raise ValueError(
                        f"Native plane section {section!r} contains {no_net_count} positive shapes without a net"
                    )
                positive_nets = {
                    row[0] for row in db.execute(
                        "SELECT DISTINCT net FROM shapes WHERE section=? AND polarity='+' AND net!=''", (section,)
                    )
                    if requested_nets is None or row[0].casefold() in requested_nets
                }
                if positive_nets:
                    found_layers.update((original.casefold(), native.casefold()))
                    sections.append((section, original, native))
                    for net in positive_nets:
                        pairs.add((native, net))
                        found_nets.add(net.casefold())
            missing_layers = sorted(requested_layers - found_layers) if requested_layers is not None else []
            missing_nets = sorted(requested_nets - found_nets) if requested_nets is not None else []
            if missing_layers or missing_nets or not pairs:
                missing = []
                if missing_layers:
                    missing.append("layers=" + ",".join(missing_layers))
                if missing_nets:
                    missing.append("nets=" + ",".join(missing_nets))
                if not pairs:
                    missing.append("no positive plane geometry selected")
                raise ValueError("Native selection did not resolve safely: " + "; ".join(missing))

            report.warn(
                "NATIVE_EXECUTION_NOT_VERIFIED",
                "SKILL was generated but must be executed and checked by Allegro 24.1",
            )
            report.warn(
                "NATIVE_PLANE_DELETE_SCOPE",
                "Each selected ETCH/BOUNDARY layer+net shape set is replaced; review shape-based routing on those pairs",
            )
            report.warn(
                "NATIVE_DYNAMIC_PLANE_RULES_NOT_RESTORED",
                "Selected planes become static copper with explicit voids. Original dynamic boundaries, "
                "clearance/thermal/repour parameters and editable shape intent cannot be recovered from SPD; "
                "unselected base-board objects and global constraints are retained.",
            )
            for key, code, label in (
                ("traces", "NATIVE_TRACES_PRESERVED", "SPD trace differences are not applied"),
                ("vias", "NATIVE_VIAS_PRESERVED", "SPD via differences are not applied"),
            ):
                count = metadata["counts"].get(key, 0)
                if count:
                    report.warn(code, f"{label}; base BRD objects remain ({count} SPD records)")
                    report.counts[f"unsupported_{key}"] = count
            component_count = len(metadata["components"])
            if component_count and not update_components:
                report.warn(
                    "NATIVE_COMPONENTS_PRESERVED",
                    f"Component placement updates disabled; base BRD placements remain ({component_count} SPD records)",
                )
            elif update_components:
                report.warn(
                    "NATIVE_COMPONENT_SET_NOT_SYNCHRONIZED",
                    "Only existing placed refdes are moved/rotated; missing, new, deleted, or side-changed components are not synchronized",
                )

            design_path = output_dir / "design.il"
            with design_path.open("w", encoding="utf-8", newline="\n") as skill:
                skill.write(_SKILL_HEADER)
                skill.write("\nprocedure(bsValidateAll()\n")
                for layer, net in sorted(pairs, key=lambda item: (item[0].casefold(), item[1].casefold())):
                    skill.write(f"  bsValidate({_skill_string(layer)} {_skill_string(net)})\n")
                skill.write("  t\n)\n\nprocedure(bsApply()\n  progn(\n")
                for layer, net in sorted(pairs, key=lambda item: (item[0].casefold(), item[1].casefold())):
                    skill.write(f"    bsDeletePlane({_skill_string(layer)} {_skill_string(net)})\n")
                for index, (section, _original, native) in enumerate(sections, 1):
                    if progress:
                        progress(f"Native bundle: plane section {index}/{len(sections)}")
                    _write_plane_calls(skill, db, section, native, requested_nets, report)
                if update_components:
                    if len(conductor_order) < 2:
                        raise ValueError("Component side validation requires distinct outer conductor layers")
                    top_layer, bottom_layer = conductor_order[0], conductor_order[-1]
                    for refdes, component in sorted(metadata["components"].items()):
                        component_layer = component.get("layer")
                        if component_layer == top_layer:
                            expected_mirrored = "nil"
                        elif component_layer == bottom_layer:
                            expected_mirrored = "t"
                        else:
                            raise ValueError(
                                f"Component {refdes!r} has missing or unsupported placement layer {component_layer!r}"
                            )
                        skill.write(
                            f"    bsUpdateComponent({_skill_string(refdes)} {_num(component['x'])} "
                            f"{_num(component['y'])} {_num(component.get('rotation', 0.0))} "
                            f"{expected_mirrored})\n"
                        )
                    report.counts["component_updates_requested"] = component_count
                skill.write("    t\n  )\n)\n\n")
                skill.write(_SKILL_FOOTER)

            (output_dir / "run.scr").write_text('skill load("design.il")\nexit\n', encoding="ascii")
            manifest = {
                "schema_version": 1,
                "backend": "allegro-24.1-skill",
                "generated_utc": datetime.now(timezone.utc).isoformat(),
                "status": "generated_unverified",
                "base_brd": "caller_supplied",
                "result_brd": "result.brd",
                "execution_result": "result.json",
                "plane_mode": "replace_static_etch_shapes",
                "selected_pairs": [{"layer": layer, "net": net} for layer, net in sorted(pairs)],
                "update_existing_components": bool(update_components),
                "unsupported": ["trace_deltas", "via_deltas", "component_add_delete", "component_side_change"],
            }
            (output_dir / "manifest.json").write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
            )
            report.counts["native_layer_net_pairs"] = len(pairs)
            report.counts["native_sections"] = len(sections)
            selected_pairs = [
                {"layer": layer, "net": net} for layer, net in sorted(pairs)
            ]
            return _write_reports(
                output_dir,
                "generated_unverified",
                report,
                {
                    "manifest_path": str((output_dir / "manifest.json").resolve()),
                    "selected_pairs": selected_pairs,
                    "update_existing_components": bool(update_components),
                },
            )
        finally:
            db.close()
    except Exception as exc:
        report.warn("NATIVE_BUNDLE_GENERATION_FAILED", str(exc))
        for filename in ("design.il", "run.scr", "manifest.json"):
            candidate = output_dir / filename
            if candidate.exists():
                candidate.unlink()
        _write_reports(output_dir, "failed", report, {"error": str(exc)})
        raise
    finally:
        if database.exists():
            database.unlink()
        journal = database.with_name(database.name + "-journal")
        if journal.exists():
            journal.unlink()
